# Generated by Django 5.2.5 on 2025-12-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_category_en_product_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_uz',
        ),
    ]
