# Generated by Django 5.2.5 on 2025-11-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
